---
title: "FlexRL-RL-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FlexRL-RL-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---






``` r
library(FlexRL)
```

`FlexRL` is a package proposing flexible probabilistic **R**ecord **L**inkage with diagnostic tools for downstream inference on linked data. The record linkage algorithm `StEM()` uses a **St**ochastic **E**xpectation **M**aximisation approach to combine 2 data sources and outputs the set of records referring to the same entities.

More details on the [record linkage methodology](https://doi.org/10.1093/jrsssc/qlaf016); on the [false discovery proportion estimation](https://doi.org/10.1002/sim.70292); and on the potential risks of downstream inference on linked data (Robach et al., in preparation).

This vignette uses example subsets from the [SHIW](https://www.bancaditalia.it/statistiche/tematiche/indagini-famiglie-imprese/bilanci-famiglie/distribuzione-microdati/index.html) data, from the [NLTCS](https://www.icpsr.umich.edu/web/NACDA/studies/9681/versions/V5) data, and synthetic data to showcase how `FlexRL` works, how `StEM()` adapts to dynamic PIVs, how `RL_diagnostics` may guide downstream inference.

We use 4 **P**artially **I**dentifying **V**ariable**s** to link the records: 2 variables such that `dynamics = "stable"` and 2 variables that may change over time. Among these 2 dynamic PIVs, we will model the changes of one (`dynamics = "structured"`) and we will let the algorithm flexible about the other (`dynamics = "flexible"`).


``` r
PIVs_config <- list( V1 = list(dynamics = "stable",
                               bound_mistakes = c(0.10,0.10),
                               fix_mistakes = c(NA,NA)),
                     V2 = list(dynamics = "stable",
                               bound_mistakes = c(0.10,0.10),
                               fix_mistakes = c(NA,NA)),
                     V3 = list(dynamics = "flexible",
                               bound_mistakes = c(NA,NA),
                               fix_mistakes = c(NA,NA)),
                     V4 = list(dynamics = "structured",
                               bound_mistakes = c(NA,NA),
                               fix_mistakes = c(0.02,0.02),
                               cond_hazard_cov = list(cov1 = c("Xe", "Xf"),
                                                      cov2 = c()))
)
PIVs <- names(PIVs_config)
PIVs_stable <- sapply(PIVs_config, function(x) x$dynamics != "structured")
PIVs_type <- list( V1 = FALSE, V2 = FALSE, V3 = FALSE, V4 = TRUE )
```

With PIVs that evolve over time, when modelling is possible, it is natural to parametrise the probability that underlying true values of the registered data for a pair of linked records coincide using a survival function. It is possible to use an exponential model, whose baseline hazard is constant in time; a Weibull model, whose baseline hazard is monotone in time; a Gompertz model, whose baseline hazard grows or decays exponentially in time; a piecewise-constant model, whose baseline hazard takes one value on each interval defined by given cut points; a custom model, supplied as a survival function `S(X, alpha, times)` together with a number of parameters and their starting values. These models may assume proportional hazards, accelerated failure time, proportional odds, additive hazards, ... If the covariates are categorical, make sure to encode them into dummies and drop one category (an intercept is included automatically). Since only the agreement of the true values at the observed time gap is used, the likelihood is the same for every model, `-sum(Hequal \* log(S) + (1 - Hequal) \* log(1 - S))`, and the parameters are estimated with `stats::nlminb()` at each M-step.


``` r
n_values  <- c(8, 9, 10, 15)
p_mistake <- list(V1 = c(0.02, 0.02), V2 = c(0.02, 0.02),
                  V3 = c(0.02, 0.02), V4 = c(0.02, 0.02))
p_missing <- list(V1 = c(0.005, 0.005), V2 = c(0.005, 0.005),
                  V3 = c(0.005, 0.005), V4 = c(0.005, 0.005))
cond_hazard_params <- list(V1 = c(), V2 = c(), V3 = c(), V4 = c(-0.35, -0.50, -0.70))

gen_data <- simulate_data(
  PIVs_config = PIVs_config, n_values = n_values, n_records = c(450, 500), 
  n_links = 400, p_mistake = p_mistake, p_missing = p_missing, 
  cond_hazard_params = cond_hazard_params, enforce_estimability = TRUE,
  model_dynamics = survival_model("exponential")
)
```

We pre-process the data for the record linkage task: remove the records for which the linking variables are outside of the common support, check that PIVs are not strongly associated with each other (which may degrade record linkage performance), map PIV values to natural numbers and encode missing values as 0. The StEM algorithm denotes the smallest source as `A` and the largest as `B`.


``` r
prep_data <- prepare_data(
  data1 = gen_data$data1, data2 = gen_data$data2, label1 = "1", label2 = "2", 
  PIVs_config = PIVs_config, same_mistakes = TRUE, uniq_id = "entity_id",
  restrict_support_intersection = TRUE
)
#> '2' is the larger source, saved as B; '1' saved as A.
```


``` r
head(prep_data$encodedA)
#>   V1 V2 V3 V4 change    date   Xe    Xf local_id entity_id source
#> 1  1  7  3  5  FALSE 0.00496 0.55  1.27        1         1      1
#> 2  3  8 10  1  FALSE 0.00036 1.49  1.77        2         2      1
#> 3  2  5  3 12  FALSE 0.00164 1.61 -0.46        3         3      1
#> 4  2  8  3  7  FALSE 0.00678 1.15  1.73        4         4      1
#> 5  5  7  2 13  FALSE 0.00604 0.48  0.30        5         5      1
#> 6  6  6  8 13  FALSE 0.00283 0.79  1.83        6         6      1
```


``` r
head(prep_data$encodedB)
#>   V1 V2 V3 V4 change   date local_id entity_id source
#> 1  8  7  3  5  FALSE 0.0090        1         1      2
#> 2  3  8 10  1  FALSE 0.0066        2         2      2
#> 3  2  5  3 12  FALSE 0.0020        3         3      2
#> 4  6  8  3  7  FALSE 0.0025        4         4      2
#> 5  1  7  2 13  FALSE 0.0076        5         5      2
#> 6  6  6  8 13  FALSE 0.0013        6         6      2
```

For this example we know the true linkage structure.


``` r
head(prep_data$true_pairs)
#>   1 2
#> 1 1 1
#> 2 2 2
#> 3 3 3
#> 4 4 4
#> 5 5 5
#> 6 6 6
```

The number of unique values per **PIV** gives information on their discriminating power:


``` r
prep_data$n_values
#> V1 V2 V3 V4 
#>  8  9 10 15
```

We gauge how hard the record linkage task is using a naive linkage approach: matching records on exact agreement of identifying information.


``` r
naive_fit <- naive_linkage(PIVs = PIVs, 
                           encodedA = prep_data$encodedA, 
                           encodedB = prep_data$encodedB)

df_results <- data.frame( matrix(NA, nrow = 11, ncol = 0) )
rownames(df_results) <- c("TP              ",
                          "FP              ",
                          "FN              ",
                          "sensitivity     ",
                          "FDP             ",
                          "hat FDP score   ",
                          "hat FDP score*  ",
                          "hat FDP synth*  ",
                          "max SMD         ",
                          "min support IoU ",
                          "max MMD         ")

true_pairs      <- do.call(paste, c(prep_data$true_pairs, list(sep="_")))
linked_pairs    <- do.call(paste, c(naive_fit, list(sep = "_")))
true_positive   <- length( intersect(linked_pairs, true_pairs) ) 
false_positive  <- length( setdiff(linked_pairs, true_pairs) ) 
false_negative  <- length( setdiff(true_pairs, linked_pairs) )
sensitivity     <- true_positive / (true_positive + false_negative) 
fdp             <- false_positive / (true_positive + false_positive) 
df_results[1:5,"Naive     "] <- c(true_positive,false_positive,false_negative,sensitivity,fdp)

df_results
#>                  Naive     
#> TP                   262.00
#> FP                    88.00
#> FN                   138.00
#> sensitivity            0.66
#> FDP                    0.25
#> hat FDP score            NA
#> hat FDP score*           NA
#> hat FDP synth*           NA
#> max SMD                  NA
#> min support IoU          NA
#> max MMD                  NA
```

We run record linkage with `FlexRL`. The `data` should contain encodedA, encodedB, n_values, PIVs_config, same_mistakes. `StEM_iter`, `StEM_burnin` and `gibbs_iter`, `gibbs_burnin` are total number of iterations (including burn-in) and iterations to be discarded as burn-in. If `music_on` the algorithm opens a short tune in the browser when it finishes. You can `save_info_iter` (save environment information at each iteration) to `new_directory`. You can set starting values of the algorithm for parameters gamma and phi with `gamma0`, `phiA0`, `phiB0`, and change the number of samples drawn a posteriori to provide a linkage estimate with `n_post_sample` (set to 1000 as default).




































