# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callFunction <- function(x, f) {
    .Call('_FlexRL_callFunction', PACKAGE = 'FlexRL', x, f)
}

ControlRandomNumberGen <- function() {
    .Call('_FlexRL_ControlRandomNumberGen', PACKAGE = 'FlexRL')
}

ControlRandomSampleGen <- function(choiceset, probavec) {
    .Call('_FlexRL_ControlRandomSampleGen', PACKAGE = 'FlexRL', choiceset, probavec)
}

F2 <- function(U, nvals) {
    .Call('_FlexRL_F2', PACKAGE = 'FlexRL', U, nvals)
}

F33 <- function(A, B, nvals) {
    .Call('_FlexRL_F33', PACKAGE = 'FlexRL', A, B, nvals)
}

sspaste2 <- function(A) {
    .Call('_FlexRL_sspaste2', PACKAGE = 'FlexRL', A)
}

F11 <- function(F, nvals) {
    .Call('_FlexRL_F11', PACKAGE = 'FlexRL', F, nvals)
}

F1 <- function(HA, HB, nvals) {
    .Call('_FlexRL_F1', PACKAGE = 'FlexRL', HA, HB, nvals)
}

sampleD <- function(S, LLA, LLB, LLL, gamma, loglik, D, nlinkrec, sumRowD, sumColD) {
    .Call('_FlexRL_sampleD', PACKAGE = 'FlexRL', S, LLA, LLB, LLL, gamma, loglik, D, nlinkrec, sumRowD, sumColD)
}

sampleNL <- function(G, eta, phi) {
    .Call('_FlexRL_sampleNL', PACKAGE = 'FlexRL', G, eta, phi)
}

sampleL <- function(GA, GB, survivalpSameH, choice_set, choice_equal, nval, phikA, phikB, eta) {
    .Call('_FlexRL_sampleL', PACKAGE = 'FlexRL', GA, GB, survivalpSameH, choice_set, choice_equal, nval, phikA, phikB, eta)
}

cartesianProduct <- function(vec1, vec2) {
    .Call('_FlexRL_cartesianProduct', PACKAGE = 'FlexRL', vec1, vec2)
}

ExpandGrid <- function(vector1, vector2) {
    .Call('_FlexRL_ExpandGrid', PACKAGE = 'FlexRL', vector1, vector2)
}

generateSequence <- function(n) {
    .Call('_FlexRL_generateSequence', PACKAGE = 'FlexRL', n)
}

sampleH <- function(nA, nB, links, survivalpSameH, pivs_stable, pivsA, pivsB, nvalues, D, nonlinkedA, nonlinkedB, eta, phi) {
    .Call('_FlexRL_sampleH', PACKAGE = 'FlexRL', nA, nB, links, survivalpSameH, pivs_stable, pivsA, pivsB, nvalues, D, nonlinkedA, nonlinkedB, eta, phi)
}

