# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
callFunction <- function(x, f) {
    .Call(`_FlexRL_callFunction`, x, f)
}

#' @export
F2 <- function(U, nvals) {
    .Call(`_FlexRL_F2`, U, nvals)
}

#' @export
F33 <- function(A, B, nvals) {
    .Call(`_FlexRL_F33`, A, B, nvals)
}

#' @export
sspaste2 <- function(A) {
    .Call(`_FlexRL_sspaste2`, A)
}

#' @export
sampleD <- function(S, LLA, LLB, LLL, gamma, loglik, D, nlinkrec, sumRowD, sumColD) {
    .Call(`_FlexRL_sampleD`, S, LLA, LLB, LLL, gamma, loglik, D, nlinkrec, sumRowD, sumColD)
}

#' @export
sampleNL <- function(G, eta, phi) {
    .Call(`_FlexRL_sampleNL`, G, eta, phi)
}

#' @export
sampleL <- function(GA, GB, survivalpSameH, choice_set, choice_equal, nval, phikA, phikB, eta) {
    .Call(`_FlexRL_sampleL`, GA, GB, survivalpSameH, choice_set, choice_equal, nval, phikA, phikB, eta)
}

#' @export
cartesianProduct <- function(vec1, vec2) {
    .Call(`_FlexRL_cartesianProduct`, vec1, vec2)
}

#' @export
ExpandGrid <- function(vector1, vector2) {
    .Call(`_FlexRL_ExpandGrid`, vector1, vector2)
}

#' @export
generateSequence <- function(n) {
    .Call(`_FlexRL_generateSequence`, n)
}

#' @export
sampleH <- function(nA, nB, links, survivalpSameH, pivs_stable, pivsA, pivsB, nvalues, nonlinkedA, nonlinkedB, eta, phi) {
    .Call(`_FlexRL_sampleH`, nA, nB, links, survivalpSameH, pivs_stable, pivsA, pivsB, nvalues, nonlinkedA, nonlinkedB, eta, phi)
}

